"""Project Generator and Manager"""

import os
from pathlib import Path
from typing import Dict, List

class ProjectGenerator:
    """Generate and manage projects"""
    
    def __init__(self, base_path: Path):
        self.base_path = base_path
        self.projects_dir = base_path / "projects"
        self.projects_dir.mkdir(parents=True, exist_ok=True)
    
    def create_project(self, name: str, language: str, 
                      description: str = "") -> Dict:
        """Create new project structure"""
        project_path = self.projects_dir / name
        project_path.mkdir(parents=True, exist_ok=True)
        
        print(f"\n📁 Creating project: {name}")
        print(f"   Language: {language}")
        print(f"   Path: {project_path}")
        
        # Create standard structure
        structure = self._get_structure(language, name)
        
        for file_path, content in structure.items():
            full_path = project_path / file_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            with open(full_path, 'w') as f:
                f.write(content)
            print(f"   ✓ {file_path}")
        
        print(f"   ✅ Project created\n")
        
        return {
            'name': name,
            'path': str(project_path),
            'language': language,
            'files': list(structure.keys())
        }
    
    def _get_structure(self, language: str, name: str) -> Dict[str, str]:
        """Get project structure template"""
        
        if language == 'python':
            return {
                'main.py': f'''#!/usr/bin/env python3
"""Main module for {name}"""

def main():
    print("Welcome to {name}!")

if __name__ == "__main__":
    main()
''',
                'requirements.txt': '# Add dependencies here\n',
                'README.md': f'# {name}\n\nGenerated by AntiGravity AI\n',
            }
        
        elif language == 'javascript':
            return {
                'index.js': f'''// Main module for {name}

function main() {{
    console.log("Welcome to {name}!");
}}

main();
''',
                'package.json': f'''{{ 
  "name": "{name.lower()}",
  "version": "1.0.0",
  "description": "Generated by AntiGravity AI",
  "main": "index.js"
}}
''',
                'README.md': f'# {name}\n\nGenerated by AntiGravity AI\n',
            }
        
        elif language == 'bash':
            return {
                'main.sh': f'''#!/bin/bash
# Main script for {name}

echo "Welcome to {name}!"
''',
                'README.md': f'# {name}\n\nGenerated by AntiGravity AI\n',
            }
        
        else:
            return {'README.md': f'# {name}\n\nGenerated by AntiGravity AI\n'}
    
    def list_projects(self) -> List[str]:
        """List all projects"""
        projects = [d.name for d in self.projects_dir.iterdir() 
                   if d.is_dir()]
        return sorted(projects)
    
    def get_project_info(self, name: str) -> Dict:
        """Get project information"""
        project_path = self.projects_dir / name
        
        if not project_path.exists():
            return {'error': f'Project {name} not found'}
        
        files = list(project_path.rglob('*'))
        
        return {
            'name': name,
            'path': str(project_path),
            'files': [str(f.relative_to(project_path)) for f in files if f.is_file()],
            'file_count': len([f for f in files if f.is_file()])
        }
